export { default as Main } from './Main';
export { default as Expertise } from './Expertise';
export { default as Education } from './Education';
export { default as Experience } from './Experience';
export { default as Project } from './Project';
export { default as Achievements } from './Achievements';
export { default as Certifications } from './Certifications';
export { default as Navigation } from './Navigation';
export { default as Footer } from './Footer';
